### ISSUE TITLE
Migration of MCM from in-tree to OOT for Azure

### ISSUE THREAD

**Issue by prashanth26** [gardener/machine-controller-manager-provider-azure#11]
**What would you like to be added**:

- [x] Develop the MCM Azure OOT code
- [x] Develop a test framework to allow testing
- [x] Write unit tests to cover the edge cases
- [x] Integrate the changes with gardener/extension-azure

**Why is this needed**:
To proceed with the mcm out of tree implementation story we need to replace the existing in-tree azure code with OOT azure.
This issue is to track the progress for the same.

/platform azure
/status in-progress

/assign @AxiomSamarth

**Comment by AxiomSamarth** [comment]
Reference PR for Gardener Extension Azure - https://github.com/gardener/gardener-extension-provider-aws/pull/212

**Comment by AxiomSamarth** [comment]
- Check for migration of machineClass without rolling update of the machines with the MCM deployed by the new extension provider azure
- Test the scale to zero and scale from zero with the MCM deployed by new extension provider azure
- keep this reference (https://github.com/gardener/gardener-extension-provider-openstack/pull/224#pullrequestreview-598228430)

**Comment by AxiomSamarth** [comment]
[PR](https://github.com/gardener/gardener-extension-provider-azure/pull/257) on Gardener Extension Provider is ready for review
