### ISSUE TITLE
There might be a bug which leads to ClusterAutoScaler fails to handle the ResourceExhausted situation

### ISSUE THREAD

**Issue by dongyingbo** [gardener/machine-controller-manager-provider-azure#111]
**What happened**:

We are creating multiple worker groups for every kind of workload so that we can fallback to other worker groups when the major one is unhealthy, resource exhausted for example.
It is hard for me to reproduce it in the real world.
But if I read the source codes correctly there might be a defect for the situation.

The provider's [CreateMachine function](https://github.com/gardener/machine-controller-manager-provider-azure/blob/0fd610967b01dc577609aa4850b359c1ff5f5a54/pkg/azure/core.go#L91) returns error code `codes.Internal` for all kind of errors.
But cluster auto scaler needs error code `codes.ResourceExhausted` [here](https://github.com/gardener/autoscaler/blob/da973f441b268ca52e01dd8fe594a8ca02d71fbe/cluster-autoscaler/cloudprovider/mcm/mcm_manager.go#L659), so that it can backoff the group when[ handleInstanceCreationErrorsForNodeGroup](https://github.com/gardener/autoscaler/blob/da973f441b268ca52e01dd8fe594a8ca02d71fbe/cluster-autoscaler/clusterstate/clusterstate.go#L1048)
[Here](https://github.com/gardener/machine-controller-manager-provider-aws/blob/e4e71ac84096a051141848e4deba29345534a964/pkg/aws/errors/utils.go#L27) is how aws provider handle with it.

**What you expected to happen**:
When resource exhausted, it should return correct error code to cluster auto scaler.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

**Comment by dongyingbo** [comment]
Similar to https://github.com/gardener/machine-controller-manager-provider-alicloud/pull/57

**Comment by rishabh-11** [comment]
Hi @dongyingbo, with https://github.com/gardener/machine-controller-manager-provider-azure/pull/105, we move to use the latest azure API. With this change we also introduce the `ResourceExhausted` error code.

**Comment by unmarshall** [comment]
In the first increment we only map `ZoneAllocationFailed`. See [here](https://github.com/gardener/machine-controller-manager-provider-azure/blob/c26394e7d3db872e9a8e1f41fd95115546a36625/pkg/azure/access/errors/errors.go#L92-L104) (This link is from the PR @rishabh-11  pointed to above, which is current under review). As and when we learn of other error codes we will keep adding to this list.

**Comment by rishabh-11** [comment]
/close

#105 is already merged and released.
