### ISSUE TITLE
Use Appropriate Error Code for timeout during VM Deletion

### ISSUE THREAD

**Issue by elankath** [gardener/machine-controller-manager-provider-azure#147]
**What would you like to be added**:

Currently, timeout during VM Deletion in Azure results in the generic error code `Internal` being returned to the MCM. See [driver.DeleteVirtualMachine](https://github.com/gardener/machine-controller-manager-provider-azure/blob/8abfac2e93bdf93c9d9ac397153be9c04bace2ca/pkg/azure/provider/helpers/driver.go#L195) .  This is then set in the `Machine.LastOperation.Description`.

We want the error code to be changed to the appropriate code [codes.DeadlineExceeded](https://github.com/gardener/machine-controller-manager/blob/0e30203dbff80e63914ec6e6da6bece3bfd8269b/pkg/util/provider/machinecodes/codes/codes.go#L55)

**Why is this needed**:
See gardener landscape issue 125
This will allow us the opportunity to use a more suitable higher level error code in gardener `ERR_INFRA_DEPENDENCIES` to avoid repetitive multiple VO alerts.

**Comment by rishabh-11** [comment]
/close

based on the comment on landscape issue 125
