### ISSUE TITLE
Azure: Improve timeout scenario during machine creation

### ISSUE THREAD

**Issue by hardikdr** [gardener/machine-controller-manager-provider-azure#40]
**What would you like to be added**: We recently faced a situation while machine-creation, where synchronous `Create()` call is waiting for a response in Azure, but the actual VM joins the cluster. The `Create()` call later times out with the following message:
```
E0806 07:21:56.635403       1 driver_azure.go:1050] Azure ARM API call with x-ms-request-id=e215fbcb-edb0-43a4-9dc6-4d021e25f84f failed. VM.WaitForCompletionRef failed for shoot-garden-az-eu1-cpu-worker-57cf885b68-zdxsv: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded
E0806 07:21:56.635492       1 machine.go:428] Error while creating machine shoot-garden-az-eu1-cpu-worker-57cf885b68-zdxsv: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded
```

As the `Create()` call to the Azure failed, MCM decides to retry the creation by deleting the running VM. 
- Another side-effect being, MCM doesn't update the machine-status until the call is returned, which could mislead the user.

**Possible solution:**  We should improve MCM to better handle the response from the [WaitForCompletionRef](https://github.com/gardener/machine-controller-manager/blob/master/pkg/driver/driver_azure.go#L606) call, possibly understand the error, and consider the operation successful if status-code 200 is seen.

**Comment by unmarshall** [comment]
MCM Provider Azure code now leverages the new Azure SDK. Therefore it needs to be observed if we see this issue again. Secondly https://github.com/gardener/machine-controller-manager/pull/868 will introduce a new taint `node.machine.sapcloud.io/instance-not-initialized` that will be placed on the node via kubelet's `--register-with-taints` that will prevent any workload to get scheduled onto the node till VM Create + VM Initialize operations have completed successfully.
