### ISSUE TITLE
Make `lun` field optional in Azure provider.

### ISSUE THREAD

**Issue by hardikdr** [gardener/machine-controller-manager-provider-azure#42]
**What would you like to be added**: With the support of multiple-worker disks in gardener/machine-controller-manager#397 , `luns` have been made required field in azuremachineclass. We might want to consider making it optional for better UX.

Refer to the [comment](https://github.com/gardener/machine-controller-manager/pull/397#discussion_r379454607) for related discussion. 

cc @dkistner

**Comment by AxiomSamarth** [comment]
This has been handled in MCM-Provider-Azure as well. [Here](https://github.com/gardener/machine-controller-manager-provider-azure/blob/4ef13f0992a0cd4cd6353e6871e97757b216c9f0/pkg/azure/utils.go#L122-L158) are the lines of code for handling the disks and even in the MachineClass ProviderSpec, [here](https://github.com/gardener/machine-controller-manager-provider-azure/blob/4ef13f0992a0cd4cd6353e6871e97757b216c9f0/pkg/azure/apis/azure_provider_spec.go#L100) the LUN is an optional field. 

@dkistner Could you please take a look and help me decide if this issue can be closed?

**Comment by dkistner** [comment]
As the `lun` can be specified optionally I guess it is ok to close.
